name: Multi-Agent Testing Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  agent-validation:
    name: Test ${{ matrix.agent }} Agent
    runs-on: ubuntu-latest
    strategy:
      matrix:
        agent: [tech-lead, product-engineer, qa-engineer, devops-specialist, doc-specialist, code-reviewer]
    
    services:
      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Test ${{ matrix.agent }} Agent
        run: npm run test:agent -- --agent=${{ matrix.agent }}
        env:
          REDIS_HOST: localhost
          REDIS_PORT: 6379
          NODE_ENV: test
      
      - name: Generate Agent Performance Report
        run: npm run eval:agent -- --agent=${{ matrix.agent }}
      
      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: agent-test-results-${{ matrix.agent }}
          path: evaluation-results/
  
  integration-test:
    name: Multi-Agent Integration Test
    runs-on: ubuntu-latest
    needs: agent-validation
    
    services:
      redis:
        image: redis:7
        ports:
          - 6379:6379
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run Integration Tests
        run: npm run test:integration
        env:
          REDIS_HOST: localhost
          REDIS_PORT: 6379
          NODE_ENV: test
      
      - name: Test Agent Collaboration
        run: npm run test:collaboration
      
      - name: Performance Benchmark
        run: npm run test:performance
      
      - name: Upload Integration Results
        uses: actions/upload-artifact@v3
        with:
          name: integration-test-results
          path: test-results/